spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: store-main
  kafka:
    bootstrap-servers:
        - localhost:9092
        - localhost:9093

server:
 port: 0
 
eureka:
 client:
  service-url:
    defaultZone: http://localhost:8761/eureka/

