spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: store-main
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

server:
 port: 0
 
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true


